version: "3.2"
services:

  memcached:
    image: memcached:alpine
    container_name: memcached-container

  mysql:
    image: mysql:5.6
    container_name: mysql_container
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - MYSQL_ROOT_PASSWORD=changeMe
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=loic
      - MYSQL_PASSWORD=changeMe
    ports:
        - "3306:3306"
      
  php-apache:
    build: phpdocker/php-apache
    container_name: apache_container
    ports:
        - 80:80
    volumes:
      - .:/app

